name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:

env:
  GCP_SQL_CONNECTION_NAME: mcp-box:us-central1:mcp-box
  GCP_CLOUD_RUN_SERVICE_NAME: mcpbox-keystone
  GCP_GAR_LOCATION: us-central1
  GCP_PROJECT_ID: mcp-box
  GCP_REGION: us-central1
  CLOUDINARY_FOLDER_ROOT: mcpbox
  DOCKER_IMAGE: ''


jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "DOCKER_IMAGE=${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Confirm environment variables
        run: |
          echo ${{ env.DOCKER_IMAGE }}


      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.DOCKER_IMAGE }}" ./
          docker push "${{ env.DOCKER_IMAGE }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ env.DOCKER_IMAGE }}
          flags: |
            --port=8080
            --timeout=300
            --allow-unauthenticated
            --add-cloudsql-instances=${{ env.GCP_SQL_CONNECTION_NAME }}
          secrets: |
            MEILISEARCH_API_KEY=MEILISEARCH_API_KEY:latest
            MEILISEARCH_HOST=MEILISEARCH_HOST:latest
            DATABASE_URL=KEYSTONE_DATABASE_URL:latest
            SESSION_SECRET=KEYSTONE_SESSION_SECRET:latest
            CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest
            CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest
            CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest
          env_vars: |
            CLOUDINARY_FOLDER_ROOT=${{ env.CLOUDINARY_FOLDER_ROOT }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Warm up service
        run: |
          for i in {1..5}; do
            curl -fsS "${{ steps.deploy.outputs.url }}" && exit 0
            echo "Retrying in 3s..."
            sleep 3
          done
          echo "Service did not respond successfully" && exit 1

      
